### ISSUE TITLE
Centos 8.3 matplotlib error

### ISSUE THREAD

**Issue by pawel1010** [vijayvarma392/black_hole_scattering#4]
$ binaryBHexp --q 2 --chiA 0.3 0.7 -0.1 --chiB 0.3 0.6 0.1 --omega_ref 1.8e-2
Loaded surfinBH7dq2 fit.
Loaded NRSur7dq2 waveform model
/usr/local/bin/binaryBHexp:614: MatplotlibDeprecationWarning: default base will change from np.e to 10 in 3.4.  To suppress this warning specify the base keyword argument.
  vmin=vmin, vmax=vmax)
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/matplotlib/backends/backend_gtk3.py", line 77, in _on_timer
    TimerBase._on_timer(self)
  File "/usr/local/lib64/python3.6/site-packages/matplotlib/backend_bases.py", line 1194, in _on_timer
    ret = func(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/matplotlib/animation.py", line 1426, in _step
    still_going = Animation._step(self, *args)
  File "/usr/local/lib64/python3.6/site-packages/matplotlib/animation.py", line 1157, in _step
    self._draw_next_frame(framedata, self._blit)
  File "/usr/local/lib64/python3.6/site-packages/matplotlib/animation.py", line 1176, in _draw_next_frame
    self._draw_frame(framedata)
  File "/usr/local/lib64/python3.6/site-packages/matplotlib/animation.py", line 1726, in _draw_frame
    self._drawn_artists = self._func(framedata, *self._args)
  File "/usr/local/bin/binaryBHexp", line 688, in update_lines
    line.set_3d_properties([])
  File "/usr/local/lib64/python3.6/site-packages/mpl_toolkits/mplot3d/art3d.py", line 143, in set_3d_properties
    zs = np.broadcast_to(zs, xs.shape)
AttributeError: 'list' object has no attribute 'shape'

(binaryBHexp:5223): GLib-CRITICAL **: 10:53:54.068: Source ID 10 was not found when attempting to remove it

**Comment by vijayvarma392** [comment]
I believe this should be fixed, please let us know if you continue to have this problem. Closing for now.
