### ISSUE TITLE
Does binaryBHexp work on MacOS or only works on Linux?

### ISSUE THREAD

**Issue by Roderick007** [vijayvarma392/black_hole_scattering#5]
<img width="1280" alt="截屏2021-05-30 下午9 08 42" src="https://user-images.githubusercontent.com/55740898/120105458-89b6b700-c18b-11eb-85ca-88c7595db20c.png">

When use command pip install binaryBHexp, the terminal reports
Failed to build gwsurrogate
Installing collected packages: gwsurrogate
    Running setup.py install for gwsurrogate ... error
......

**Comment by duetosymmetry** [comment]
Please provide text logs of errors instead of a screen shot.

This particular error is that your system does not have the GSL (GNU Scientific Library) installed. You can install GSL system-wide with `brew install gsl` (if you use [homebrew](https://brew.sh/)), or within a conda environment with `conda install gsl` (if you use some conda flavor; anaconda should include gsl in its base installation, but since you encounter this error, that means you are not using anaconda, or did not activate it).

**Comment by Roderick007** [comment]
Thanks a lot, successfully installed GSL and binaryBHexp already. But a new error reported when I run the command binaryBHexp --q 1.34 --chiA 0.62 -0.27 0.34 --chiB -0.62 0.27 0.34:

caosizheng@caosizhengdeMacBook-Pro ~ % sudo binaryBHexp --q 1.34 --chiA 0.62 -0.27 0.34 --chiB -0.62 0.27 0.34
No display found. Using non-interactive Agg backend
Downloading surfinBH7dq2 data
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1342, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1122)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/binaryBHexp", line 1137, in <module>
    line_ani = BBH_animation(fig, args.q, args.chiA, args.chiB,
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/binaryBHexp", line 766, in BBH_animation
    fit = surfinBH.LoadFits(fit_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/surfinBH/_loadFits.py", line 34, in LoadFits
    DownloadData(name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/surfinBH/_loadFits.py", line 69, in DownloadData
    urlretrieve(data_url, data_dir + '/' + filename)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1385, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1345, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1122)>

**Comment by Roderick007** [comment]
> Please provide text logs of errors instead of a screen shot.
> 
> This particular error is that your system does not have the GSL (GNU Scientific Library) installed. You can install GSL system-wide with `brew install gsl` (if you use [homebrew](https://brew.sh/)), or within a conda environment with `conda install gsl` (if you use some conda flavor; anaconda should include gsl in its base installation, but since you encounter this error, that means you are not using anaconda, or did not activate it).



Thanks a lot, successfully installed GSL and binaryBHexp already. But a new error reported when I run the command binaryBHexp --q 1.34 --chiA 0.62 -0.27 0.34 --chiB -0.62 0.27 0.34:

caosizheng@caosizhengdeMacBook-Pro ~ % sudo binaryBHexp --q 1.34 --chiA 0.62 -0.27 0.34 --chiB -0.62 0.27 0.34
No display found. Using non-interactive Agg backend
Downloading surfinBH7dq2 data
Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1342, in do_open
h.request(req.get_method(), req.selector, req.data, headers,
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1255, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1301, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1250, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1010, in _send_output
self.send(msg)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 950, in send
self.connect()
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1424, in connect
self.sock = self._context.wrap_socket(self.sock,
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
return self.sslsocket_class._create(
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
self.do_handshake()
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1122)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.9/bin/binaryBHexp", line 1137, in
line_ani = BBH_animation(fig, args.q, args.chiA, args.chiB,
File "/Library/Frameworks/Python.framework/Versions/3.9/bin/binaryBHexp", line 766, in BBH_animation
fit = surfinBH.LoadFits(fit_name)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/surfinBH/_loadFits.py", line 34, in LoadFits
DownloadData(name)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/surfinBH/_loadFits.py", line 69, in DownloadData
urlretrieve(data_url, data_dir + '/' + filename)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 239, in urlretrieve
with contextlib.closing(urlopen(url, data)) as fp:
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
return opener.open(url, data, timeout)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 517, in open
response = self._open(req, data)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 534, in _open
result = self._call_chain(self.handle_open, protocol, protocol +
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
result = func(*args)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1385, in https_open
return self.do_open(http.client.HTTPSConnection, req,
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1345, in do_open
raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1122)>

**Comment by vijayvarma392** [comment]
I'm able to run on MacOS with no issues. As this issue is probably outdated by now, I'm closing it, but let us know if you continue to have trouble.
